BTLNhom10/Models/Tuyendung.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BTLNhom10.Models;

[Table("Tuyendungs")]
public class Tuyendung
{
    [Key]
    [Required(ErrorMessage ="ID không được bỏ trống")]
    [Display(Name = "Mã quản lý")]
    public string MaQL { get; set; }

    [Required(ErrorMessage ="Phòng ban không được bỏ trống")]
    [Display(Name = "Phòng ban")]
    public string PhongBan { get; set; }


     [Required(ErrorMessage ="Độ tuổi không được bỏ trống")]
     [Display(Name = "Độ tuổi")]
    public string DoTuoi { get; set; }
     
     [Required(ErrorMessage ="kinh nghiệm không được bỏ trống")]
     [Display(Name = "Kinh nghiệm")]
    public string NamKN { get; set; }
    
    [Required(ErrorMessage ="Trình độ không được bỏ trống")]
     [Display(Name = "Trình độ")]
    public string TrinhDo { get; set; }
    
    [Required(ErrorMessage ="Ngoại hình không được bỏ trống")]
     [Display(Name = "Ngoại hình")]
    public string NgoaiHinh { get; set; }
    
    [Required(ErrorMessage ="Ngoại ngữ không được bỏ trống")]
     [Display(Name = "Ngoại ngữ")]
     public string NgoaiNgu { get; set; }

  
     [Display(Name = "Phỏng vấn")]
     public string PhongVan { get; set; }


     [Display(Name = "Yêu cầu")]
    public string YeuCau { get; set; }
     
     
}

BTLNhom10/Controllers/TuyendungController.cs
using BTLNhom10.Data;
using BTLNhom10.Models;
using BTLNhom10.Models.Process;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using X.PagedList;

namespace BTLNhom10.Controllers{
    public class TuyendungController : Controller
    {
        private readonly ApplicationDbcontext _context;
        public TuyendungController(ApplicationDbcontext context){
            _context=context;
        }
         private ExcelProcess _excelPro = new ExcelProcess();
        public async Task<IActionResult> Index(int? page, int? PageSize )
        {
            ViewBag.PageSize = new List<SelectListItem>()
            {
                
                new SelectListItem() { Value="5",Text= "5"},
                new SelectListItem() { Value="10",Text= "10"},
                new SelectListItem() { Value="15",Text= "15"},
                new SelectListItem() { Value="25",Text= "25"},
                new SelectListItem() { Value="50",Text= "50"},
                
        
            };
            int pagesize = (PageSize ?? 3);
            ViewBag.psize = pagesize;
            var model = _context.Tuyendung.ToList().ToPagedList(page ?? 1, pagesize);
            return View(model);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Tuyendung == null)
            {
                return NotFound();
            }

            var tuyendung = await _context.Tuyendung
                .FirstOrDefaultAsync(m => m.MaQL == id);
            if (tuyendung == null)
            {
                return NotFound();
            }

            return View(tuyendung);
        }

        public IActionResult Create(){
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind("MaQL, PhongBan, DoTuoi, NamKN, TrinhDo, NgoaiHinh, NgoaiNgu, PhongVan, YeuCau ")] Tuyendung tuyendung){
            if(ModelState.IsValid){
                _context.Add(tuyendung);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tuyendung);
        }
        public async Task<IActionResult> Edit(String id)
        {
            if (id == null || _context.Tuyendung == null)
            {
                return NotFound();
            }
            var tuyendung = await _context.Tuyendung.FindAsync(id);
            if (tuyendung == null)
            {
                return NotFound();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(String id, [Bind("MaQL, PhongBan, DoTuoi, NamKN, TrinhDo, NgoaiHinh, NgoaiNgu, PhongVan, YeuCau")] Tuyendung tuyendung){
            if (id !=tuyendung.MaQL){
                return NotFound();
            }
            if (ModelState.IsValid){
                try{
                    _context.Update(tuyendung);
                    await _context.SaveChangesAsync();
                }catch(DbUpdateConcurrencyException){
                    if (!TuyendungExists(tuyendung.MaQL)){
                        return NotFound();
                    }else{
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private bool TuyendungExists(string id)
        {
            return (_context.Tuyendung?.Any(e=>e.MaQL==id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(String id)
        {
            if(id==null || _context.Tuyendung == null){
                return NotFound();
            }
            var tuyendung = await _context.Tuyendung.FirstOrDefaultAsync(m => m.MaQL == id);
            if (tuyendung ==  null){
                return NotFound();
            }
            return View(tuyendung);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConFirmed(String id){
            if(_context.Tuyendung==null){
                return Problem ("Entity set 'ApplicationDbcontext.Tuyendung' is null." );
            }
            var tuyendung = await _context.Tuyendung.FindAsync(id);
            if (tuyendung !=null)
            {
                _context.Tuyendung.Remove(tuyendung);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file!=null)
                {
                    string fileExtension = Path.GetExtension(file.FileName);
                    if (fileExtension != ".xls" && fileExtension != ".xlsx")
                    {
                        ModelState.AddModelError("", "Please choose excel file to upload!");
                    }
                    else
                    {
                        //rename file when upload to server
                        var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excels", "File" + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Millisecond + fileExtension);
                        var fileLocation = new FileInfo(filePath).ToString();
                        if (file.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                //save file to server
                                await file.CopyToAsync(stream);
                                //read data from file and write to database
                                var dt = _excelPro.ExcelToDataTable(fileLocation);
                                for(int i = 0; i < dt.Rows.Count; i++)
                                {
                                    var td = new Tuyendung();
                                    td.MaQL = dt.Rows[i][0].ToString();
                                    td.PhongBan = dt.Rows[i][1].ToString();
                                    td.DoTuoi = dt.Rows[i][2].ToString();
                                    td.NamKN = dt.Rows[i][3].ToString();
                                    td.TrinhDo = dt.Rows[i][4].ToString();
                                    td.NgoaiHinh = dt.Rows[i][5].ToString();
                                    td.NgoaiNgu = dt.Rows[i][6].ToString();
                                    td.PhongVan = dt.Rows[i][7].ToString();
                                     td.YeuCau = dt.Rows[i][8].ToString();
                                    _context.Add(td);
                                }
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
            
            return View();
        }  
         public IActionResult Download()
        {
            var fileName = "TuyendungList.xlsx";
            using(ExcelPackage excelPackage = new ExcelPackage())
            {
                ExcelWorksheet excelWorksheet = excelPackage.Workbook.Worksheets.Add("Sheet 1");
                excelWorksheet.Cells["A1"].Value = "MaQL";
                excelWorksheet.Cells["B1"].Value = "PhongBan";
                excelWorksheet.Cells["C1"].Value = "DoTuoi";
                excelWorksheet.Cells["D1"].Value = "NamKN";
                excelWorksheet.Cells["E1"].Value = "TrinhDo";
                excelWorksheet.Cells["F1"].Value = "NgoaiHinh";
                excelWorksheet.Cells["G1"].Value = "NgoaiNgu";
                excelWorksheet.Cells["H1"].Value = "PhongVan";
                excelWorksheet.Cells["I1"].Value = "YeuCau";
                var tdList = _context.Tuyendung.ToList();
                excelWorksheet.Cells["A2"].LoadFromCollection(tdList);
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                return File(stream,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);
            }
        }  
    }

}

BTLNhom10/Views/Tuyendung/Create.cshtml
@model BTLNhom10.Models.Tuyendung

@{
    ViewData["Title"] = "Create";
}

<h1>Tạo dữ liệu mới</h1>


<hr >
<form asp-action="Upload" enctype="multipart/form-data">
        <div class="row form-control">
            <label class="col-md-2">Nhập vào file Excel: </label>
            <input type="file" name="file" class="col-sm-4">
            <input type="submit" value="Upload" class="btn btn-primary col-md-1">
        </div>
    </form>
    <hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaQL" class="control-label"></label>
                <input asp-for="MaQL" class="form-control" />
                <span asp-validation-for="MaQL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhongBan" class="control-label"></label>
                <input asp-for="PhongBan" class="form-control" />
                <span asp-validation-for="PhongBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoTuoi" class="control-label"></label>
                <input  asp-for="DoTuoi" class="form-control" />
                <span asp-validation-for="DoTuoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamKN" class="control-label"></label>
                <input asp-for="NamKN" class="form-control" />
                <span asp-validation-for="NamKN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrinhDo" class="control-label"></label>
                <input  asp-for="TrinhDo" class="form-control" />
                <span asp-validation-for="TrinhDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgoaiHinh" class="control-label"></label>
                <input  asp-for="NgoaiHinh" class="form-control" />
                <span asp-validation-for="NgoaiHinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgoaiNgu" class="control-label"></label>
                <input asp-for="NgoaiNgu" class="form-control" />
                <span asp-validation-for="NgoaiNgu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhongVan" class="control-label"></label>
                <input asp-for="PhongVan" class="form-control" />
                <span asp-validation-for="PhongVan" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="YeuCau" class="control-label"></label>
                <input asp-for="YeuCau" class="form-control" />
                <span asp-validation-for="YeuCau" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                @* <input type="submit" value="Create" class="btn btn-primary" /> *@
                @* <input type="button" class="w3-button w3-black" value="Save" style="margin-top: 30px;"> *@
                 <p><button class="w3-button w3-dark-grey" style="margin-top: 30px;">Lưu dữ liệu</button></p>
            </div>
        </form>
    </div>
</div>

<div>
    @* <a asp-action="Index" >Back to List</a> *@
    @* <input type="button" class="w3-button w3-Dark-Grey" value="Back to list" style="margin-top: 20px;"> *@
    <p><button class="w3-button w3-dark-grey" style="margin-top: 10px;">Quay lại</button></p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
@* NguyenHongQuan-1921050489  *@

BTLNhom10/Views/Tuyendung/Delete.cshtml
@model BTLNhom10.Models.Tuyendung

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa thông tin</h1>

<h3>Bạn có chắc chắn muốn xóa bản ghi này ? </h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaQL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaQL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhongBan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhongBan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoTuoi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoTuoi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamKN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamKN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrinhDo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrinhDo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgoaiHinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgoaiHinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgoaiNgu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgoaiNgu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhongVan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhongVan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YeuCau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YeuCau)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaQL" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Quay lại</a>
    </form>
</div>


NguyenHongQuan-1921050489 

BTLNhom10/Views/Tuyendung/Details.cshtml
@model BTLNhom10.Models.Tuyendung

@{
    ViewData["Title"] = "Details";
}

<h1>Chi tiết dữ liệu</h1>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhongBan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhongBan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoTuoi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoTuoi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamKN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamKN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrinhDo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrinhDo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgoaiHinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgoaiHinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgoaiNgu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgoaiNgu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhongVan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhongVan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YeuCau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YeuCau)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaQL">Sửa</a> |
    <a asp-action="Index">Quay lại</a>
</div>
NguyenHongQuan-1921050489

BTLNhom10/Views/Tuyendung/Edit.cshtml
@model BTLNhom10.Models.Tuyendung

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa thông tin</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaQL" />
            <div class="form-group">
                <label asp-for="PhongBan" class="control-label"></label>
                <input asp-for="PhongBan" class="form-control" />
                <span asp-validation-for="PhongBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoTuoi" class="control-label"></label>
                <input  asp-for="DoTuoi" class="form-control" />
                <span asp-validation-for="DoTuoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamKN" class="control-label"></label>
                <input asp-for="NamKN" class="form-control" />
                <span asp-validation-for="NamKN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrinhDo" class="control-label"></label>
                <input asp-for="TrinhDo" class="form-control" />
                <span asp-validation-for="TrinhDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgoaiHinh" class="control-label"></label>
                <input asp-for="NgoaiHinh" class="form-control" />
                <span asp-validation-for="NgoaiHinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgoaiNgu" class="control-label"></label>
                <input asp-for="NgoaiNgu" class="form-control" />
                <span asp-validation-for="NgoaiNgu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhongVan" class="control-label"></label>
                <input asp-for="PhongVan" class="form-control" />
                <span asp-validation-for="PhongVan" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="YeuCau" class="control-label"></label>
                <input asp-for="YeuCau" class="form-control" />
                <span asp-validation-for="YeuCau" class="text-danger"></span>
            </div>
            
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
NguyenHongQuan-1921050489

BTLNhom10/Views/Tuyendung/Index.cshtml
@model IEnumerable<BTLNhom10.Models.Tuyendung>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


 <div class="w3-container ">
    <div class="w3-row w3-teal w3-table">
        <h1 style="margin-left:30px;">Dữ liệu tuyển dụng</h1>
         <a asp-action="Create" class="w3-btn w3-border w3-border-white w3-round w3-tiny w3-horver-blue" >Thêm bảng mới</a> 
          <a asp-action="Download" class="w3-btn w3-border w3-border-white w3-round w3-right w3-tiny w3-horver-blue">Tải xuống</a>

    </div>
    <hr/>
    <table  class="w3-table w3-panel w3-border w3-border-blue w3-panel w3-card" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PhongBan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoTuoi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NamKN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrinhDo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgoaiHinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgoaiNgu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhongVan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YeuCau)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
    
            @foreach (var item in Model)
            {
                
                <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PhongBan)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.DoTuoi)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.NamKN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrinhDo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgoaiHinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgoaiNgu)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.PhongVan)
            </td>
              <td>
                @Html.DisplayFor(modelItem => item.YeuCau)
            </td>
          
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaQL">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.MaQL">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.MaQL">Xóa</a>
            </td>
        </tr>
            }
        </tbody>
    </table>
      <a asp-action="Download" class="w3-btn w3-border w3-border-white w3-round w3-right w3-tiny w3-horver-blue">Tải xuống</a> 
  
 @using (Html.BeginForm("Index", "Tuyendung", FormMethod.Get, new { id="form1"})){
    <div class="row">
        <div class="col-md-11">
            @Html.PagedListPager((IPagedList) Model, page => Url.Action("Index", new {page = page,
            pageSize= ViewBag.psize}), 
            new X.PagedList.Web.Common.PagedListRenderOptions { LiElementClasses = new string[] {"page-item"}, 
            PageClasses = new string[] { "page-link" }})
        </div>
        <div class="col-md-1">
            @Html.DropDownList("pagesize", null, new {@class="form-select"})
        </div>
    </div>

}
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function(){
        $("#pagesize").change(function(){
            $("#form1").submit();
        });
    });
</script>  

</div>  
  
       

NguyenHongQuan-1921050489