BTLNhom10/Models/Luong.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BTLNhom10.Models;

[Table("Luongs")]
public class Luong
{
    [Key]
    [Required(ErrorMessage ="ID không được bỏ trống")]
    [Display(Name = "Mã nhân viên")]
    public string MaNV { get; set; }

    [Required(ErrorMessage ="Họ và tên không được bỏ trống")]
    [Display(Name = "Họ và tên")]
    public string TenNV { get; set; }

    [Required(ErrorMessage ="Lương không được bỏ trống")]
    [Display(Name = "Lương cơ bản")]
    public int LuongCoBan { get; set; }

    [Required(ErrorMessage ="Phụ cấp không được bỏ trống")]
    [Display(Name = "Phụ cấp")]
    public int PhuCap { get; set; }

    [Required(ErrorMessage ="Hệ số lương không được bỏ trống")]
    [Display(Name = "Hệ số lương")]
    public int HeSoLuong { get; set; }

    
    [Display(Name = "Lương chuyên cần")]
     public int LuongChuyenCan { get; set; }
    

}

BTLNhom10/Controllers/LuongController.cs
using BTLNhom10.Data;
using BTLNhom10.Models;
using BTLNhom10.Models.Process;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using X.PagedList;

namespace BTLNhom10.Controllers{
    public class LuongController : Controller
    {
        private readonly ApplicationDbcontext _context;
        public LuongController(ApplicationDbcontext context){
            _context=context;
        }
         private ExcelProcess _excelPro = new ExcelProcess();
        public async Task<IActionResult> Index(int? page, int? PageSize )
        {
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="3",Text= "3"},
                new SelectListItem() { Value="5",Text= "5"},
                new SelectListItem() { Value="10",Text= "10"},
                new SelectListItem() { Value="15",Text= "15"},
                new SelectListItem() { Value="25",Text= "25"},
                new SelectListItem() { Value="50",Text= "50"},
                
        
            };
            int pagesize = (PageSize ?? 3);
            ViewBag.psize = pagesize;
            var model = _context.Luong.ToList().ToPagedList(page ?? 1, pagesize);
            return View(model);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Luong == null)
            {
                return NotFound();
            }

            var luong = await _context.Luong
                .FirstOrDefaultAsync(m => m.MaNV == id);
            if (luong == null)
            {
                return NotFound();
            }

            return View(luong);
        }

        public IActionResult Create(){
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind("MaNV, TenNV, LuongCoBan, PhuCap, HeSoLuong, LuongChuyenCan")] Luong luong){
            if(ModelState.IsValid){
                _context.Add(luong);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(luong);
        }
        public async Task<IActionResult> Edit(String id)
        {
            if (id == null || _context.Luong == null)
            {
                return NotFound();
            }
            var luong = await _context.Luong.FindAsync(id);
            if (luong == null)
            {
                return NotFound();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(String id, [Bind("MaNV, TenNV, LuongCoBan, PhuCap, HeSoLuong, LuongChuyenCan")] Luong luong){
            if (id !=luong.MaNV){
                return NotFound();
            }
            if (ModelState.IsValid){
                try{
                    _context.Update(luong);
                    await _context.SaveChangesAsync();
                }catch(DbUpdateConcurrencyException){
                    if (!LuongExists(luong.MaNV)){
                        return NotFound();
                    }else{
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private bool LuongExists(string id)
        {
            return (_context.Luong?.Any(e=>e.MaNV==id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(String id)
        {
            if(id==null || _context.Luong == null){
                return NotFound();
            }
            var luong = await _context.Luong.FirstOrDefaultAsync(m => m.MaNV == id);
            if (luong ==  null){
                return NotFound();
            }
            return View(luong);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConFirmed(String id){
            if(_context.Luong==null){
                return Problem ("Entity set 'ApplicationDbcontext.Luong' is null." );
            }
            var luong = await _context.Luong.FindAsync(id);
            if (luong !=null)
            {
                _context.Luong.Remove(luong);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file!=null)
                {
                    string fileExtension = Path.GetExtension(file.FileName);
                    if (fileExtension != ".xls" && fileExtension != ".xlsx")
                    {
                        ModelState.AddModelError("", "Please choose excel file to upload!");
                    }
                    else
                    {
                        //rename file when upload to server
                        var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excels", "File" + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Millisecond + fileExtension);
                        var fileLocation = new FileInfo(filePath).ToString();
                        if (file.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                //save file to server
                                await file.CopyToAsync(stream);
                                //read data from file and write to database
                                var dt = _excelPro.ExcelToDataTable(fileLocation);
                                for(int i = 0; i < dt.Rows.Count; i++)
                                {
                                    var lg = new Luong();
                                    lg.MaNV = dt.Rows[i][0].ToString();
                                    lg.TenNV = dt.Rows[i][1].ToString();
                                    lg.LuongCoBan = Convert.ToInt32(dt.Rows[i][2].ToString());
                                    lg.PhuCap = Convert.ToInt32(dt.Rows[i][3].ToString());
                                    lg.HeSoLuong = Convert.ToInt32(dt.Rows[i][4].ToString());
                                    lg.LuongChuyenCan = Convert.ToInt32(dt.Rows[i][5].ToString());
                                    
                                    _context.Add(lg);
                                }
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
            
            return View();
        }  
         public IActionResult Download()
        {
            var fileName = "LuongList.xlsx";
            using(ExcelPackage excelPackage = new ExcelPackage())
            {
                ExcelWorksheet excelWorksheet = excelPackage.Workbook.Worksheets.Add("Sheet 1");
                excelWorksheet.Cells["A1"].Value = "MaNV";
                excelWorksheet.Cells["B1"].Value = "TenNV";
                excelWorksheet.Cells["C1"].Value = "LuongCoBan";
                excelWorksheet.Cells["D1"].Value = "PhuCap";
                excelWorksheet.Cells["E1"].Value = "HeSoLuong";
                excelWorksheet.Cells["F1"].Value = "LuongChuyenCan";
               
                var lgList = _context.Luong.ToList();
                excelWorksheet.Cells["A2"].LoadFromCollection(lgList);
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                return File(stream,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);
            }
        }  
    }

}

BTLNhom10/Views/Luong/Create.cshtml
@model BTLNhom10.Models.Luong

@{
    ViewData["Title"] = "Create";
}

<h1>Tạo dữ liệu mới</h1>


<hr>
<form asp-action="Upload" enctype="multipart/form-data">
        <div class="row form-control">
            <label class="col-md-2">Mời nhập vào file Excel:</label>
            <input type="file" name="file" class="col-sm-4">
            <input type="submit" value="Upload" class="btn btn-primary col-md-1">
        </div>
    </form>
    <hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaNV" class="control-label"></label>
                <input asp-for="MaNV" class="form-control" />
                <span asp-validation-for="MaNV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenNV" class="control-label"></label>
                <input asp-for="TenNV" class="form-control" />
                <span asp-validation-for="TenNV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuongCoBan" class="control-label"></label>
                <input asp-for="LuongCoBan" class="form-control" />
                <span asp-validation-for="LuongCoBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhuCap" class="control-label"></label>
                <input asp-for="PhuCap" class="form-control" />
                <span asp-validation-for="PhuCap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HeSoLuong" class="control-label"></label>
                <input asp-for="HeSoLuong" class="form-control" />
                <span asp-validation-for="HeSoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuongChuyenCan" class="control-label"></label>
                <input asp-for="LuongChuyenCan" class="form-control" />
                <span asp-validation-for="LuongChuyenCan" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                @* <input type="submit" value="Create" class="btn btn-primary" /> *@
                @* <input type="button" class="w3-button w3-black" value="Save" style="margin-top: 30px;"> *@
                 <p><button class="w3-button w3-dark-grey" style="margin-top: 30px;">Lưu dữ liệu</button></p>
            </div>
        </form>
    </div>
</div>

<div>
    @* <a asp-action="Index" >Back to List</a> *@
    @* <input type="button" class="w3-button w3-Dark-Grey" value="Back to list" style="margin-top: 20px;"> *@
    <p><button class="w3-button w3-dark-grey" style="margin-top: 20px;">Quay lại</button></p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
NguyenHongQuan-1921050489

BTLNhom10/Views/Luong/Delete.cshtml
@model BTLNhom10.Models.Luong

@{
    ViewData["Title"] = "Delete";
}

<h1>Bảng lương</h1>

<h3>Bạn có chắc chắn muốn xóa bản ghi này ?</h3>
<div>
    <h4>Lương</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuongCoBan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuongCoBan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhuCap)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhuCap)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HeSoLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HeSoLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuongChuyenCan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuongChuyenCan)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaNV" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Quay lại</a>
    </form>
</div>
NguyenHongQuan-1921050489

BTLNhom10/Views/Luong/Details.cshtml
@model BTLNhom10.Models.Luong

@{
    ViewData["Title"] = "Details";
}

<h1>Chi tiết dữ liệu</h1>

<div>
    <h4>Nhan vien</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuongCoBan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuongCoBan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhuCap)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhuCap)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HeSoLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HeSoLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuongChuyenCan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuongChuyenCan)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaNV">Edit</a> |
    <a asp-action="Index">Quay lại</a>
</div>

BTLNhom10/Views/Luong/Edit.cshtml
@model BTLNhom10.Models.Luong

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaNV" />
            <div class="form-group">
                <label asp-for="TenNV" class="control-label"></label>
                <input asp-for="TenNV" class="form-control" />
                <span asp-validation-for="TenNV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuongCoBan" class="control-label"></label>
                <input asp-for="LuongCoBan" class="form-control" />
                <span asp-validation-for="LuongCoBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhuCap" class="control-label"></label>
                <input asp-for="PhuCap" class="form-control" />
                <span asp-validation-for="PhuCap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HeSoLuong" class="control-label"></label>
                <input asp-for="HeSoLuong" class="form-control" />
                <span asp-validation-for="HeSoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuongChuyenCan" class="control-label"></label>
                <input asp-for="LuongChuyenCan" class="form-control" />
                <span asp-validation-for="LuongChuyenCan" class="text-danger"></span>
            </div>
            
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
NguyenHongQuan-1921050489

BTLNhom10/Views/Luong/Index.cshtml
@model IEnumerable<BTLNhom10.Models.Luong>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="w3-container ">
    <div class="w3-row w3-teal">
        <h1 style="margin-left:30px;">Dữ liệu lương</h1>
        <a asp-action="Create" class="w3-btn w3-border w3-border-white w3-round w3-tiny w3-horver-blue" >Thêm bảng mới</a> 
        <a asp-action="Download" class="w3-btn w3-border w3-border-white w3-round w3-right w3-tiny w3-horver-blue">Download</a>

    </div>
    <hr/>
    <table class="table w3-panel w3-border w3-border-blue w3-panel w3-card" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LuongCoBan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhuCap)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HeSoLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LuongChuyenCan)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
    
            @foreach (var item in Model)
            {
                
                <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenNV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LuongCoBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhuCap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HeSoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LuongChuyenCan)
            </td>
            
          
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaNV">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.MaNV">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.MaNV">Xóa</a>
            </td>
        </tr>
            }
        </tbody>
    </table>
      
 @using (Html.BeginForm("Index", "Luong", FormMethod.Get, new { id="form1"})){
    <div class="row">
        <div class="col-md-11">
            @Html.PagedListPager((IPagedList) Model, page => Url.Action("Index", new {page = page,
            pageSize= ViewBag.psize}), 
            new X.PagedList.Web.Common.PagedListRenderOptions { LiElementClasses = new string[] {"page-item"}, 
            PageClasses = new string[] { "page-link" }})
        </div>
        <div class="col-md-1">
            @Html.DropDownList("pagesize", null, new {@class="form-select"})
        </div>
    </div>

}
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function(){
        $("#pagesize").change(function(){
            $("#form1").submit();
        });
    });
</script>  

</div>

NguyenHongQuan-1921050489