BTLNhom10/Models/Chamcong.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BTLNhom10.Models;

[Table("Chamcongs")]
public class Chamcong
{
    [Key]
    [Required(ErrorMessage ="ID không được bỏ trống")]
    [Display(Name = "Mã nhân viên")]
    public string MaNV { get; set; }
     
     [Required(ErrorMessage ="Họ Và Tên không được bỏ trống")]
     [Display(Name = "Họ và tên")]
    public string TenNV { get; set; }
    
    [Required(ErrorMessage ="Ngày nghỉ không được bỏ trống")]
     [Display(Name = "Ngày nghỉ phép")]
    public int NgayNghiPhep { get; set; }
    
    [Required(ErrorMessage ="Số ngày công không được bỏ trống")]
     [Display(Name = "Số ngày công")]
    public int SoNgayCong { get; set; }
    
    [Required(ErrorMessage ="Số giờ công không được bỏ trống")]
     [Display(Name = "Số giờ công")]
     public int SoGioCong { get; set; }
     
}

BTLNhom10/Controllers/ChamcongController.cs
using BTLNhom10.Data;
using BTLNhom10.Models;
using BTLNhom10.Models.Process;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using X.PagedList;

namespace BTLNhom10.Controllers{
    public class ChamcongController : Controller
    {
        private readonly ApplicationDbcontext _context;
        public ChamcongController(ApplicationDbcontext context){
            _context = context;
        }
         private ExcelProcess _excelPro = new ExcelProcess();
        public async Task<IActionResult> Index(int? page, int? PageSize )
        {
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="3",Text= "3"},
                new SelectListItem() { Value="5",Text= "5"},
                new SelectListItem() { Value="10",Text= "10"},
                new SelectListItem() { Value="15",Text= "15"},
                new SelectListItem() { Value="25",Text= "25"},
                new SelectListItem() { Value="50",Text= "50"},
                
        
            };
            int pagesize = (PageSize ?? 3);
            ViewBag.psize = pagesize;
            var model = _context.Chamcong.ToList().ToPagedList(page ?? 1, pagesize);
            return View(model);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Chamcong == null)
            {
                return NotFound();
            }

            var chamcong = await _context.Chamcong
                .FirstOrDefaultAsync(m => m.MaNV == id);
            if (chamcong == null)
            {
                return NotFound();
            }

            return View(chamcong);
        }

        public IActionResult Create(){
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind("MaNV, TenNV, NgayNghiPhep, SoNgayCong, SoGioCong")] Chamcong chamcong){
            if(ModelState.IsValid){
                _context.Add(chamcong);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chamcong);
        }
        public async Task<IActionResult> Edit(String id)
        {
            if (id == null || _context.Chamcong == null)
            {
                return NotFound();
            }
            var chamcong = await _context.Chamcong.FindAsync(id);
            if (chamcong == null)
            {
                return NotFound();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(String id, [Bind("MaNV, TenNV, NgayNghiPhep, SoNgayCong, SoGioCong")] Chamcong chamcong){
            if (id !=chamcong.MaNV){
                return NotFound();
            }
            if (ModelState.IsValid){
                try{
                    _context.Update(chamcong);
                    await _context.SaveChangesAsync();
                }catch(DbUpdateConcurrencyException){
                    if (!ChamcongExists(chamcong.MaNV)){
                        return NotFound();
                    }else{
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private bool ChamcongExists(string id)
        {
            return (_context.Chamcong?.Any(e=>e.MaNV==id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(String id)
        {
            if(id==null || _context.Chamcong == null){
                return NotFound();
            }
            var chamcong = await _context.Chamcong.FirstOrDefaultAsync(m => m.MaNV == id);
            if (chamcong ==  null){
                return NotFound();
            }
            return View(chamcong);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConFirmed(String id){
            if(_context.Chamcong==null){
                return Problem ("Entity set 'ApplicationDbcontext.Chamcong' is null." );
            }
            var chamcong = await _context.Chamcong.FindAsync(id);
            if (chamcong !=null)
            {
                _context.Chamcong.Remove(chamcong);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file!=null)
                {
                    string fileExtension = Path.GetExtension(file.FileName);
                    if (fileExtension != ".xls" && fileExtension != ".xlsx")
                    {
                        ModelState.AddModelError("", "Please choose excel file to upload!");
                    }
                    else
                    {
                        //rename file when upload to server
                        var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excels", "File" + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Millisecond + fileExtension);
                        var fileLocation = new FileInfo(filePath).ToString();
                        if (file.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                //save file to server
                                await file.CopyToAsync(stream);
                                //read data from file and write to database
                                var dt = _excelPro.ExcelToDataTable(fileLocation);
                                for(int i = 0; i < dt.Rows.Count; i++)
                                {
                                    var cc = new Chamcong();
                                    cc.MaNV = dt.Rows[i][0].ToString();
                                    cc.TenNV = dt.Rows[i][1].ToString();
                                    cc.NgayNghiPhep = Convert.ToInt32(dt.Rows[i][2].ToString());
                                    cc.SoNgayCong = Convert.ToInt32(dt.Rows[i][3].ToString());
                                    cc.SoGioCong = Convert.ToInt32(dt.Rows[i][4].ToString());
                                    
                                    
                                    _context.Add(cc);
                                }
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
            
            return View();
        }  
         public IActionResult Download()
        {
            var fileName = "ChamcongList.xlsx";
            using(ExcelPackage excelPackage = new ExcelPackage())
            {
                ExcelWorksheet excelWorksheet = excelPackage.Workbook.Worksheets.Add("Sheet 1");
                excelWorksheet.Cells["A1"].Value = "MaNV";
                excelWorksheet.Cells["B1"].Value = "TenNV";
                excelWorksheet.Cells["C1"].Value = "NgayNghiPhep";
                excelWorksheet.Cells["D1"].Value = "SoNgayCong";
                excelWorksheet.Cells["E1"].Value = "SoGioCong";
              
               
                var ccList = _context.Chamcong.ToList();
                excelWorksheet.Cells["A2"].LoadFromCollection(ccList);
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                return File(stream,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);
            }
        }  
    }

}

BTLNhom10/Views/Chamcong/Create.cshtml
@model BTLNhom10.Models.Chamcong

@{
    ViewData["Title"] = "Create";
}

<div class="w3-row w3-teal col-md-2">
    
        <h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:20px ">Thêm dữ liệu mới</h2>
</div>



<hr>
<form asp-action="Upload" enctype="multipart/form-data">
        <div class="row form-control">
            <label class="col-md-2">Nhập vào file Excel: </label>
            <input type="file" name="file" class="col-sm-4">
            <input type="submit" value="Upload" class="btn btn-primary col-md-1" style="margin-left: -200px;">
        </div>
    </form>
    <hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaNV" class="control-label"></label>
                <input asp-for="MaNV" class="form-control" />
                <span asp-validation-for="MaNV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenNV" class="control-label"></label>
                <input asp-for="TenNV" class="form-control" />
                <span asp-validation-for="TenNV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayNghiPhep" class="control-label"></label>
                <input asp-for="NgayNghiPhep" class="form-control" />
                <span asp-validation-for="NgayNghiPhep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoNgayCong" class="control-label"></label>
                <input asp-for="SoNgayCong" class="form-control" />
                <span asp-validation-for="SoNgayCong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoGioCong" class="control-label"></label>
                <input asp-for="SoGioCong" class="form-control" />
                <span asp-validation-for="SoGioCong" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                @* <input type="submit" value="Create" class="btn btn-primary" /> *@
                @* <input type="button" class="w3-button w3-black" value="Save" style="margin-top: 30px;"> *@
                 <p><button class="w3-button w3-dark-grey" style="margin-top: 30px;">Lưu dữ liệu</button></p>
            </div>
        </form>
    </div>
</div>

<div>
    @* <a asp-action="Index" >Back to List</a> *@
    @* <input type="button" class="w3-button w3-Dark-Grey" value="Back to list" style="margin-top: 20px;"> *@
    <p><button class="w3-button w3-dark-grey" style="margin-top: 20px;">Quay lại</button></p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<p style="margin-top: 200px">NguyenHongQuan-1921050489</p>

BTLNhom10/Views/Chamcong/Delete.cshtml
@model BTLNhom10.Models.Chamcong

@{
    ViewData["Title"] = "Delete";
}

<div class="w3-row w3-teal col-md-2">
    
        <h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:20px ">Xóa bản ghi</h2>
</div>

<h3>Bạn có chắc chắn muốn xóa bản ghi này ?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayNghiPhep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayNghiPhep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoNgayCong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoNgayCong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoGioCong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoGioCong)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaNV" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
       
    </form>
    <p><a asp-action="Index" ><button  class="w3-button w3-dark-grey" style="margin-top: 20px;">Quay lại</button></a></p>
</div>
NguyenHongQuan-1921050489

BTLNhom10/Views/Chamcong/Details.cshtml
@model BTLNhom10.Models.Chamcong

@{
    ViewData["Title"] = "Details";
}

<div class="w3-row w3-teal col-md-2">
    
        <h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:20px ">Chi tiết chấm công</h2>
</div>

<div>
    <h4>Chấm công</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayNghiPhep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayNghiPhep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoNgayCong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoNgayCong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoGioCong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoGioCong)
        </dd>
        
    </dl>
</div>
<div>
   <a asp-action="Edit" asp-route-id="@Model?.MaNV" class="w3-button w3-teal">Sửa</a> |
    <a asp-action="Index" class="w3-button w3-teal">Quay lại</a>
</div>

BTLNhom10/Views/Chamcong/Edit.cshtml
@model BTLNhom10.Models.Chamcong

@{
    ViewData["Title"] = "Edit";
}

<div class="w3-row w3-teal col-md-2">
    
        <h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:20px ">Sửa thông tin</h2>
</div>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaNV" />
            <div class="form-group">
                <label asp-for="TenNV" class="control-label"></label>
                <input asp-for="TenNV" class="form-control" />
                <span asp-validation-for="TenNV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayNghiPhep" class="control-label"></label>
                <input asp-for="NgayNghiPhep" class="form-control" />
                <span asp-validation-for="NgayNghiPhep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoNgayCong" class="control-label"></label>
                <input asp-for="SoNgayCong" class="form-control" />
                <span asp-validation-for="SoNgayCong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoGioCong" class="control-label"></label>
                <input asp-for="SoGioCong" class="form-control" />
                <span asp-validation-for="SoGioCong" class="text-danger"></span>
            </div>
            
            
            <div class="form-group">
                @* <input type="submit" value="Save" class="btn btn-primary" /> *@
                <input type="submit" value="Lưu thông tin" class="btn btn-primary " style="margin-top: 20px;" />
            </div>
        </form>
    </div>
</div>

<div>
  <a asp-action="Index" ><button  class="w3-button w3-blue w3-holver" style="margin-top: 20px;">Quay lại</button></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
NguyenHongQuan-1921050489

BTLNhom10/Views/Chamcong/Index.cshtml
@model IEnumerable<BTLNhom10.Models.Chamcong>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* <div class="w3-container ">
    <div class="w3-row w3-teal">
        <h1 style="margin-left:30px;">Dữ liệu chấm công</h1>
        <a asp-action="Create" class="w3-btn w3-border w3-border-white w3-round w3-tiny w3-horver-blue" >Thêm bảng mới</a> 
        <a asp-action="Download" class="w3-btn w3-border w3-border-white w3-round w3-right w3-tiny w3-horver-blue">Tải xuống</a>

    </div> *@
    <div class="w3-container ">
    <div class="w3-row w3-teal">
        
        <h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:40px ">Dữ liệu chấm công</h2>
</div>
    <a asp-action="Create" ><button  class="w3-button w3-btn w3-border-white w3-grey w3-horver-blue" style="margin-top: 20px;">Thêm bảng mới</button></a>
    <hr/>
    <table class="table w3-panel w3-border w3-border-blue w3-panel w3-card" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayNghiPhep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoNgayCong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoGioCong)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
    
            @foreach (var item in Model)
            {
                
                <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenNV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayNghiPhep)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoNgayCong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoGioCong)
            </td>
            
          
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaNV" class="w3-button w3-teal">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.MaNV" class="w3-button w3-teal">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.MaNV" class="w3-button w3-teal">Xóa</a>
            </td>
        </tr>
            }
        </tbody>
    </table>
      
 @using (Html.BeginForm("Index", "Chamcong", FormMethod.Get, new { id="form1"})){
    <div class="row">
        <div class="col-md-11">
            @Html.PagedListPager((IPagedList) Model, page => Url.Action("Index", new {page = page,
            pageSize= ViewBag.psize}), 
            new X.PagedList.Web.Common.PagedListRenderOptions { LiElementClasses = new string[] {"page-item"}, 
            PageClasses = new string[] { "page-link" }})
        </div>
        <div class="col-md-1">
            @Html.DropDownList("pagesize", null, new {@class="form-select"})
        </div>
    </div>

}
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function(){
        $("#pagesize").change(function(){
            $("#form1").submit();
        });
    });
</script>  

</div>
<a asp-action="Download" ><button  class="w3-button w3-dark-grey" style="margin-top: 20px;">Tải xuống</button></a>
<p style="margin-top: 200px;">NguyenHongQuan-1921050489</p>