BTLNhom10/Models/Quanlyhoso.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BTLNhom10.Models;

[Table("Quanlyhosos")]
public class Quanlyhoso
{
    [Key]
     [Required(ErrorMessage ="ID không được bỏ trống")]
    [Display(Name = "Mã nhân viên")]
    public string MaNV { get; set; }

     [Required(ErrorMessage ="Họ và tên không được bỏ trống")]
    [Display(Name = "Họ và tên")]
    public string TenNV { get; set; }

    [Required(ErrorMessage ="Ngày sinh không được bỏ trống")]
    [Display(Name = "Ngày sinh")]
    public string SinhNgay { get; set; }

     [Required(ErrorMessage ="Ngày làm việc không được bỏ trống")]
    [Display(Name = "Ngày làm việc")]
    public string NgayLamViec { get; set; }
     
     [Required(ErrorMessage ="Email không được bỏ trống")]
    [Display(Name = "Email")]
    public string Email { get; set; }

     [Required(ErrorMessage ="Số điện thoại không được bỏ trống")]
    [Display(Name = "Số điện thoại")]
     public string SoDienThoai { get; set; }

      [Required(ErrorMessage ="Số tài khoản không được bỏ trống")]
    [Display(Name = "Số tài khoản")]
     public int SoTaiKhoan { get; set; }

      [Required(ErrorMessage ="Phòng ban không được bỏ trống")]
    [Display(Name = "Phòng ban")]
     public string PhongBan { get; set; }

      
}

BTLNhom10/Controllers/NhanvienController.cs
using BTLNhom10.Data;
using BTLNhom10.Models;
using BTLNhom10.Models.Process;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using X.PagedList;

namespace BTLNhom10.Controllers{
    public class NhanvienController : Controller
    {
        private readonly ApplicationDbcontext _context;
        public NhanvienController(ApplicationDbcontext context){
            _context=context;
        }
         private ExcelProcess _excelPro = new ExcelProcess();
        public async Task<IActionResult> Index(int? page, int? PageSize )
        {
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="3",Text= "3"},
                new SelectListItem() { Value="5",Text= "5"},
                new SelectListItem() { Value="10",Text= "10"},
                new SelectListItem() { Value="15",Text= "15"},
                new SelectListItem() { Value="25",Text= "25"},
                new SelectListItem() { Value="50",Text= "50"},
                
        
            };
            int pagesize = (PageSize ?? 3);
            ViewBag.psize = pagesize;
            var model = _context.Nhanvien.ToList().ToPagedList(page ?? 1, pagesize);
            return View(model);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Nhanvien == null)
            {
                return NotFound();
            }

            var nhanvien = await _context.Nhanvien
                .FirstOrDefaultAsync(m => m.MaNV == id);
            if (nhanvien == null)
            {
                return NotFound();
            }

            return View(nhanvien);
        }

        public IActionResult Create(){
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind("MaNV, TenNV, QueQuan, Tuoi, GioiTinh, NamKN, ChucVu")] Nhanvien nhanvien){
            if(ModelState.IsValid){
                _context.Add(nhanvien);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nhanvien);
        }
        public async Task<IActionResult> Edit(String id)
        {
            if (id == null || _context.Nhanvien == null)
            {
                return NotFound();
            }
            var nhanvien = await _context.Nhanvien.FindAsync(id);
            if (nhanvien == null)
            {
                return NotFound();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(String id, [Bind("MaNV, TenNV, QueQuan, Tuoi, GioiTinh, NamKN, ChucVu")] Nhanvien nhanvien){
            if (id !=nhanvien.MaNV){
                return NotFound();
            }
            if (ModelState.IsValid){
                try{
                    _context.Update(nhanvien);
                    await _context.SaveChangesAsync();
                }catch(DbUpdateConcurrencyException){
                    if (!NhanvienExists(nhanvien.MaNV)){
                        return NotFound();
                    }else{
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private bool NhanvienExists(string id)
        {
            return (_context.Nhanvien?.Any(e=>e.MaNV==id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(String id)
        {
            if(id==null || _context.Nhanvien == null){
                return NotFound();
            }
            var nhanvien = await _context.Nhanvien.FirstOrDefaultAsync(m => m.MaNV == id);
            if (nhanvien ==  null){
                return NotFound();
            }
            return View();
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConFirmed(String id){
            if(_context.Nhanvien==null){
                return Problem ("Entity set 'ApplicationDbcontext.Nhanvien' is null." );
            }
            var nhanvien = await _context.Nhanvien.FindAsync(id);
            if (nhanvien !=null)
            {
                _context.Nhanvien.Remove(nhanvien);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file!=null)
                {
                    string fileExtension = Path.GetExtension(file.FileName);
                    if (fileExtension != ".xls" && fileExtension != ".xlsx")
                    {
                        ModelState.AddModelError("", "Please choose excel file to upload!");
                    }
                    else
                    {
                        //rename file when upload to server
                        var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excels", "File" + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Millisecond + fileExtension);
                        var fileLocation = new FileInfo(filePath).ToString();
                        if (file.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                //save file to server
                                await file.CopyToAsync(stream);
                                //read data from file and write to database
                                var dt = _excelPro.ExcelToDataTable(fileLocation);
                                for(int i = 0; i < dt.Rows.Count; i++)
                                {
                                    var nv = new Nhanvien();
                                    nv.MaNV = dt.Rows[i][0].ToString();
                                    nv.TenNV = dt.Rows[i][1].ToString();
                                    nv.QueQuan = dt.Rows[i][2].ToString();
                                    nv.Tuoi = Convert.ToInt32(dt.Rows[i][3].ToString());
                                    nv.GioiTinh = dt.Rows[i][4].ToString();
                                    nv.NamKN = dt.Rows[i][5].ToString();
                                    nv.ChucVu = dt.Rows[i][6].ToString();
                                    _context.Add(nv);
                                }
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
            
            return View();
        }  
         public IActionResult Download()
        {
            var fileName = "NhanvienList.xlsx";
            using(ExcelPackage excelPackage = new ExcelPackage())
            {
                ExcelWorksheet excelWorksheet = excelPackage.Workbook.Worksheets.Add("Sheet 1");
                excelWorksheet.Cells["A1"].Value = "MaNV";
                excelWorksheet.Cells["B1"].Value = "TenNV";
                excelWorksheet.Cells["C1"].Value = "QueQuan";
                excelWorksheet.Cells["D1"].Value = "Tuoi";
                excelWorksheet.Cells["E1"].Value = "GioiTinh";
                excelWorksheet.Cells["F1"].Value = "NamKN";
                excelWorksheet.Cells["G1"].Value = "ChucVu";
                var nvList = _context.Nhanvien.ToList();
                excelWorksheet.Cells["A2"].LoadFromCollection(nvList);
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                return File(stream,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);
            }
        }  
    }

}

BTLNhom10/Controllers/QuanlyhosoController.cs
using BTLNhom10.Data;
using BTLNhom10.Models;
using BTLNhom10.Models.Process;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using X.PagedList;

namespace BTLNhom10.Controllers{
    public class QuanlyhosoController : Controller
    {
        private readonly ApplicationDbcontext _context;
        public QuanlyhosoController(ApplicationDbcontext context){
            _context=context;
        }
         private ExcelProcess _excelPro = new ExcelProcess();
        public async Task<IActionResult> Index(int? page, int? PageSize )
        {
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="3",Text= "3"},
                new SelectListItem() { Value="5",Text= "5"},
                new SelectListItem() { Value="10",Text= "10"},
                new SelectListItem() { Value="15",Text= "15"},
                new SelectListItem() { Value="25",Text= "25"},
                new SelectListItem() { Value="50",Text= "50"},
                
        
            };
            int pagesize = (PageSize ?? 3);
            ViewBag.psize = pagesize;
            var model = _context.Quanlyhoso.ToList().ToPagedList(page ?? 1, pagesize);
            return View(model);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Quanlyhoso == null)
            {
                return NotFound();
            }

            var quanlyhoso = await _context.Quanlyhoso
                .FirstOrDefaultAsync(m => m.MaNV == id);
            if (quanlyhoso == null)
            {
                return NotFound();
            }

            return View(quanlyhoso);
        }

        public IActionResult Create(){
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind("MaNV, TenNV, SinhNgay, NgayLamViec, Email, SoDienThoai, SoTaiKhoan, PhongBan")] Quanlyhoso quanlyhoso){
            if(ModelState.IsValid){
                _context.Add(quanlyhoso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quanlyhoso);
        }
        public async Task<IActionResult> Edit(String id)
        {
            if (id == null || _context.Quanlyhoso == null)
            {
                return NotFound();
            }
            var quanlyhoso = await _context.Quanlyhoso.FindAsync(id);
            if (quanlyhoso == null)
            {
                return NotFound();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(String id, [Bind("MaNV, TenNV, SinhNgay, NgayLamViec, Email, SoDienThoai, SoTaiKhoan, PhongBan")] Quanlyhoso quanlyhoso){
            if (id !=quanlyhoso.MaNV){
                return NotFound();
            }
            if (ModelState.IsValid){
                try{
                    _context.Update(quanlyhoso);
                    await _context.SaveChangesAsync();
                }catch(DbUpdateConcurrencyException){
                    if (!QuanlyhosoExists(quanlyhoso.MaNV)){
                        return NotFound();
                    }else{
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private bool QuanlyhosoExists(string id)
        {
            return (_context.Quanlyhoso?.Any(e=>e.MaNV==id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(String id)
        {
            if(id==null || _context.Quanlyhoso == null){
                return NotFound();
            }
            var quanlyhoso = await _context.Quanlyhoso.FirstOrDefaultAsync(m => m.MaNV == id);
            if (quanlyhoso ==  null){
                return NotFound();
            }
            return View(quanlyhoso);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConFirmed(String id){
            if(_context.Quanlyhoso==null){
                return Problem ("Entity set 'ApplicationDbcontext.Quanlyhoso' is null." );
            }
            var quanlyhoso = await _context.Quanlyhoso.FindAsync(id);
            if (quanlyhoso !=null)
            {
                _context.Quanlyhoso.Remove(quanlyhoso);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file!=null)
                {
                    string fileExtension = Path.GetExtension(file.FileName);
                    if (fileExtension != ".xls" && fileExtension != ".xlsx")
                    {
                        ModelState.AddModelError("", "Please choose excel file to upload!");
                    }
                    else
                    {
                        //rename file when upload to server
                        var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excels", "File" + DateTime.Now.Day + DateTime.Now.Hour + DateTime.Now.Minute + DateTime.Now.Millisecond + fileExtension);
                        var fileLocation = new FileInfo(filePath).ToString();
                        if (file.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                //save file to server
                                await file.CopyToAsync(stream);
                                //read data from file and write to database
                                var dt = _excelPro.ExcelToDataTable(fileLocation);
                                for(int i = 0; i < dt.Rows.Count; i++)
                                {
                                    var ql = new Quanlyhoso();
                                    ql.MaNV = dt.Rows[i][0].ToString();
                                    ql.TenNV = dt.Rows[i][1].ToString();
                                    ql.SinhNgay = dt.Rows[i][2].ToString();
                                    ql.NgayLamViec = dt.Rows[i][3].ToString();
                                    ql.Email = dt.Rows[i][4].ToString();
                                    ql.SoDienThoai = dt.Rows[i][5].ToString();
                                    ql.SoTaiKhoan = Convert.ToInt32(dt.Rows[i][6].ToString());
                                    ql.PhongBan = dt.Rows[i][7].ToString();
                                    
                                    _context.Add(ql);
                                }
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
            
            return View();
        }  
         public IActionResult Download()
        {
            var fileName = "QuanlyhosoList.xlsx";
            using(ExcelPackage excelPackage = new ExcelPackage())
            {
                ExcelWorksheet excelWorksheet = excelPackage.Workbook.Worksheets.Add("Sheet 1");
                excelWorksheet.Cells["A1"].Value = "MaNV";
                excelWorksheet.Cells["B1"].Value = "TenNV";
                excelWorksheet.Cells["C1"].Value = "Email";
                excelWorksheet.Cells["D1"].Value = "SoDienThoai";
                excelWorksheet.Cells["E1"].Value = "SoTaiKhoan";
                excelWorksheet.Cells["F1"].Value = "PhongBan";
               
                var qlList = _context.Quanlyhoso.ToList();
                excelWorksheet.Cells["A2"].LoadFromCollection(qlList);
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                return File(stream,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",fileName);
            }
        }  
    }

}

BTLNhom10/Views/Quanlyhoso/Details.cshtml
@model BTLNhom10.Models.Quanlyhoso

@{
    ViewData["Title"] = "Details";
}

<div class="w3-row w3-teal col-md-2">
    
        <h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:20px ">Chi tiết dữ liệu</h2>
</div>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenNV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SinhNgay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SinhNgay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayLamViec)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayLamViec)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoTaiKhoan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoTaiKhoan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhongBan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhongBan)
        </dd>
        
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model?.MaNV">Sửa</a> |
    <a asp-action="Index">Quay lại</a> *@
     <a asp-action="Edit" asp-route-id="@Model?.MaNV" class="w3-button w3-teal">Sửa</a> |
    <a asp-action="Index" class="w3-button w3-teal">Quay lại</a>
</div>
NguyenHongQuan-1921050489

BTLNhom10/Views/Quanlyhoso/Index.cshtml
@* @model IEnumerable<BTLNhom10.Models.Quanlyhoso>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="w3-container ">
    <div class="w3-row w3-teal">
        <h1 style="margin-left:30px;">Dữ liệu chấm công</h1>
        <a asp-action="Create" class="w3-btn w3-border w3-border-white w3-round w3-tiny w3-horver-blue" >Thêm bảng mới</a> 
        <a asp-action="Download" class="w3-btn w3-border w3-border-white w3-round w3-right w3-tiny w3-horver-blue">Tải xuống</a>

    </div>
    <hr/>
    <table class="table w3-panel w3-border w3-border-blue w3-panel w3-card" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SinhNgay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayLamViec)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoTaiKhoan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhongBan)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
    
            @foreach (var item in Model)
            {
                
                <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenNV)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.SinhNgay)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.NgayLamViec)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoTaiKhoan)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.PhongBan)
            </td>
          
            <td>
                <a><button asp-action="Edit" asp-route-id="@item.MaNV" class="w3-button w3-teal">Sửa</button></a> |
                
                <a><button asp-action="Details" asp-route-id="@item.MaNV" class="w3-button w3-teal">Chi tiết</button></a> |
                <a><button asp-action="Delete" asp-route-id="@item.MaNV" class="w3-button w3-teal">Xóa</button></a>
            </td>
        </tr>
            }
        </tbody>
    </table>
      
 @using (Html.BeginForm("Index", "Quanlyhoso", FormMethod.Get, new { id="form1"})){
    <div class="row">
        <div class="col-md-11">
            @Html.PagedListPager((IPagedList) Model, page => Url.Action("Index", new {page = page,
            pageSize= ViewBag.psize}), 
            new X.PagedList.Web.Common.PagedListRenderOptions { LiElementClasses = new string[] {"page-item"}, 
            PageClasses = new string[] { "page-link" }})
        </div>
        <div class="col-md-1">
            @Html.DropDownList("pagesize", null, new {@class="form-select"})
        </div>
    </div>

}
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function(){
        $("#pagesize").change(function(){
            $("#form1").submit();
        });
    });
</script>  

</div>

NguyenHongQuan-1921050489 *@
@model IEnumerable<BTLNhom10.Models.Quanlyhoso>
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="w3-container ">
    <div class="w3-row w3-teal">
        
        <h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:40px ">Quản lý hồ sơ</h2>
</div>
    <a asp-action="Create" ><button  class="w3-button w3-btn w3-border-white w3-grey w3-horver-blue" style="margin-top: 20px;">Thêm bảng mới</button></a>
    <hr/>
    <table class="w3-table w3-panel w3-border w3-border-blue w3-panel w3-card" >
    <thead>
        <tr>
            <th >
                @Html.DisplayNameFor(model => model.TenNV)
            </th>
            <th >
                @Html.DisplayNameFor(model => model.SinhNgay)
            </th>
            <th style="text-align: center;">
                @Html.DisplayNameFor(model => model.NgayLamViec)
            </th>
            <th style="text-align: center;">
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th style="text-align: center;">
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th style="text-align: center;">
                @Html.DisplayNameFor(model => model.SoTaiKhoan)
            </th>
            <th >
                @Html.DisplayNameFor(model => model.PhongBan)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    
            @foreach (var item in Model)
            {
                
                <tr>
            <td >
                @Html.DisplayFor(modelItem => item.TenNV)
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.SinhNgay)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.NgayLamViec)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.SoTaiKhoan)
            </td>
             <td >
                @Html.DisplayFor(modelItem => item.PhongBan)
            </td>
          
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaNV" class="w3-button w3-teal">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.MaNV" class="w3-button w3-teal">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.MaNV" class="w3-button w3-teal">Xóa</a>
            </td>
        </tr>
            }
        </tbody>
    </table>
      
 @using (Html.BeginForm("Index", "Nhanvien", FormMethod.Get, new { id="form1"})){
    <div class="row">
        <div class="col-md-11">
            @Html.PagedListPager((IPagedList) Model, page => Url.Action("Index", new {page = page,
            pageSize= ViewBag.psize}), 
            new X.PagedList.Web.Common.PagedListRenderOptions { LiElementClasses = new string[] {"page-item"}, 
            PageClasses = new string[] { "page-link" }})
        </div>
        <div class="col-md-1">
            @Html.DropDownList("pagesize", null, new {@class="form-select"})
        </div>
    </div>

}
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
    $(document).ready(function(){
        $("#pagesize").change(function(){
            $("#form1").submit();
        });
    });
</script>  

</div>
@* <p ><a style="margin-right: 1200px " asp-action="Download" class="w3-btn w3-border w3-border-green w3-round w3-right w3-tiny w3-horver-blue ">Tải xuống</a></p> *@
 <a asp-action="Download" ><button  class="w3-button w3-dark-grey" style="margin-top: 20px;">Tải xuống</button></a>



<p style="margin-top: 150px;">NguyenHongQuan-1921050489</p>